#!/usr/bin/bash
set -eu
default_account=bm1233
valid_partitions=("compute" "gpu")
default_partition="compute"
usage=$(cat << EOF
Usage: $0 [-h] EMAIL [PARTITION] [ACCOUNT]

Generates user-specific run scripts for miniWeather based on existing templates.

Required arguments:
    EMAIL    The email address to which Slurm status messages are sent.

Optional arguments:
    -h
    --help     Print a usage message and exit.

    PARTITION  Group of nodes to request (default: ${default_partition}).
               The following partitions are valid: ${valid_partitions[@]}
               Only ONE of those can be provided. 
               If you specify 'shared', then your openmp and/or mpi simulations
               may not start.
               See https://docs.dkrz.de/doc/levante/running-jobs/partitions-and-limits.html

    ACCOUNT    DKRZ account identifier for Slurm jobs (default: ${default_account})

Examples:
    $0 -h                                # outputs help information
    $0 myemail@gmail.com                 # specifies valid email address 
    $0 myemail@gmail.com compute         # specifies compute partition
    $0 myemail@gmail.com compute bm1233  # specifies account for Slurm jobs
EOF
)

# Get script arguments
email=${1:-"invalid"}

if [[ "${email}" == "-h" || "${email}" == "--help" ]]
then
    echo "${usage}"
    exit 0 
fi

if [[ "${email}" == "invalid" || ! "${email}" =~ .+"@".+ ]]
then
    echo "[ERROR] Invalid EMAIL provided"
    echo "  See $0 -h"
    exit 1 
fi

partition=${2:-$default_partition}

is_invalid_partition=1
for valid_partition in ${valid_partitions[@]}
do
    if [[ "${partition}" == "${valid_partition}" ]]
    then
        is_invalid_partition=0
        break
    fi
done

if [[ ${is_invalid_partition} -eq 1 ]]
then
    echo "[ERROR] Invalid PARTITION provided"
    echo "  See $0 -h"
    exit 1 
fi

account=${3:-$default_account}

# Project directories 
fortran_project_dir="$(dirname $(dirname $(dirname $(realpath ${BASH_SOURCE[0]}))))"
fortran_scripts_dir="${fortran_project_dir}/scripts"
run_dir="${fortran_scripts_dir}/run"
templates_dir="${fortran_scripts_dir}/templates"

# Replace fields in templates to generate runnable Slurm scripts
for f in $(ls "${templates_dir}"/* )
do
    if [[ "${f}" == *".template" ]]
    then
        basename_f=$(basename $f)
        run_script="${run_dir}/${partition}_${basename_f/.template/}"
        sed "s/ACCOUNT/${account}/" "${f}" > "${run_script}"
        sed -i "s/EMAIL/${email}/" "${run_script}" 
        sed -i "s/PARTITION/${partition}/" "${run_script}"
        sed -i "s,FORTRAN_PROJECT_DIR,${fortran_project_dir}," "${run_script}"
        chmod +x "${run_script}"
    fi
done 

echo "[SUCCESS] See ${run_dir} for generated files"
